version: '3'
services:
  boot:
    build: .
    image: kad
    ports:
    - "8080:8080"
    entrypoint: ./kademlia -s 8080
  node1:
    build: .
    image: kad
    depends_on: 
      - boot
    ports:
      - "8081:8081"
    links: 
      - boot
    command: ./kademlia -s 8081
  # node2:
  #   build: .
  #   image: kad
    # depends_on: 
    #   - boot
  #   ports:
  #   - "8082:8082"
  #   command: ./kademlia -s 8082
