version: '3'
services:
  boot:
    build: .
    image: kad
    ports:
    - "8080:8080"
    entrypoint: ./kademlia -s boot 8080
  node1:
    build: .
    image: kad
    depends_on: 
      - boot
    ports:
      - "8081:8081"
    links: 
      - boot
    command: ./kademlia -s node1 8081
  node2:
    build: .
    image: kad
    depends_on: 
      - boot
      - node1
    links: 
      - node1
      - boot
    ports:
    - "8082:8082"
    command: ./kademlia -s node2 8082
